### ISSUE TITLE
Include code from Jingyu

### ISSUE THREAD

**Issue by iangow** [iangow/wrds_pg#20]
@Jessiezjy:

What code did you run to test your commits? Which tables did you update (or attempt to update)?

**Comment by Jessiezjy** [comment]
@iangow:
Sorry. I didn't notice the misalignment typo. The new version should be OK. I tested it on ubuntu trying to update all the tables in update_comp.py. $python3 update_comp.py

**Comment by iangow** [comment]
Thanks.

I will test it a little at my end and then merge. I guess that after that, we could run other parts of the code. Some things I will need to update (e.g., the Audit Analytics code in the `audit` directory is still based on the older Perl code that this Python code has replaced).
