### ISSUE TITLE
diroffichange & auditnonreli

### ISSUE THREAD

**Issue by MichaelRec** [iangow/wrds_pg#3]
Hi Ian,

The update script does not work with diroffichange & auditnonreli (others are just doing great). It seems to be a problem with csv. However it works well with other tables. 

Here is the error message for auditnonreli.

Updated audit.auditnonreli is available.Getting from WRDS.
Getting schema for audit.auditnonreli
NOTICE:  schema "audit" already exists, skipping
NOTICE:  table "auditnonreli" does not exist, skipping
Beginning file import at 11:26:56
Importing data into audit.auditnonreli.
ERROR:  missing data for column "matchfy_balsh_cash_equivs"
CONTEXT:  COPY auditnonreli, line 2: ",,|3|8|11|14|24|44|46|69|,"|PPE intangible or fixed asset (value/diminution) issues|Financial deriva..."
Result of system command: 256

I am using Mac, postgres 9.4.5 and perl 5.23.2

**Comment by iangow** [comment]
Those tables are difficult to work with. There are custom scripts in the `audit` director to deal with these (at least `diroffichange`).
