### ISSUE TITLE
Create SAS-to-PG function

### ISSUE THREAD

**Issue by iangow** [iangow/wrds_pg#40]
I think this should not be too difficult and would be worthwhile to have. I will add some guidance in comments below.

**Comment by iangow** [comment]
I think the first step would be to make a local version of the `get_process` function found in `wrds_fetch.py` (say, `get_local_process(sas_code)`). This would be much simpler than the existing function, which pipes the SAS code to an SSH connection to WRDS. I could probably take a look at that over the weekend or early next week (too busy before then).

I think [this](https://stackoverflow.com/questions/41238273/execute-shell-command-with-pipes-in-python) may be useful. (In fact, I think I adapted the `get_process` from similar ideas in the first place.)

**Comment by jingyujzhang** [comment]
Added a workable version. I tested it using sas default table `sasuser.admit` and pushed this table to `public` schema successfully. Need to continue working on it.

**Comment by jingyujzhang** [comment]
Updated the 1st version.
